### ISSUE TITLE
Pulse dos veces para editar

### ISSUE THREAD

**Issue by EkoHakou** [JSMonroe/Node-S-Web#1]
Deja un comentario.
![20200411_023824_copy_328x314](https://user-images.githubusercontent.com/93357978/139562700-0c3d69e4-68c8-4c59-a887-bda81a7d6907.png)

**Comment by JSMonroe** [comment]
Mames xd

**Comment by EkoHakou** [comment]
ㅤㅤㅤㅤㅤㅤㅤㅤㅤ

**Comment by EkoHakou** [comment]
> Mames xd
ㅤㅤㅤㅤㅤㅤㅤㅤㅤ

**Comment by EkoHakou** [comment]
Duplicate of #

**Comment by EkoHakou** [comment]
![20210517_202256](https://user-images.githubusercontent.com/93357978/139700393-3aa4ad8e-01d4-4626-b652-58189b3c4f1b.jpg)
